import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { PageLink } from "@/types/link.types";

interface Props {
    children: React.ReactNode;
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function setHeaderLinks(pageLinks: PageLink[]) {
    return pageLinks.map((link) => {
        return (
            <li key={`link-${link.href}`}>
                <Link href={link.href}>{link.text}</Link>
            </li>
        );
    });
}

const pageLinks: PageLink[] = [
    { text: "Inicio", href: "/" },
    { text: "Tienda", href: "/tienda" },
    { text: "Contacto", href: "/contacto" },
    { text: "Como comprar", href: "/como-comprar" },
    { text: "Iniciar sesion", href: "/iniciar-sesion" },
    { text: "Registrarse", href: "/registrarse" },
    { text: "Recuperar contraseña", href: "recuperar-contrasena" },
];

export default function RootLayout(props: Props) {
    return (
        <html lang="es">
            <body>
                <header>
                    <ul>{setHeaderLinks(pageLinks)}</ul>
                </header>
                <br />
                <br />
                <hr />
                <main>{props.children}</main>
                <br />
                <br />
                <hr />
                <footer>Page footer</footer>
            </body>
        </html>
    );
}
